- hosts: localhost
  vars:
    source_key: "./.ssh/ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/ed25519"
    projects: "{{ lookup('env', 'HOME') }}/projects"
  pre_tasks:
  - name: Update 
    become: false
    when: ansible_facts['os_family'] == "Darwin"
    ansible.builtin.command: echo "Beginning MacOS Setup"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/nvim.yml
  #   apt:
  #     force_apt_get: true
  #     update_cache: true
  #     state: present
  #   tags:
  #     - install
  #     - core
  # tasks:
  #   - TODO
