- name: Install brew
  become: true
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:  ansible_facts['os_family'] == "Darwin
  tags:
    - install
    - brew

