- name: Remove neovim
  shell: rm -rf ~/neovim
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  become: true
  apt: name=luarocks
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
